[package]
name = "rust_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["cargo", "derive"] }
color = "0.3.1"
colored="2"
rayon="1.10"
anyhow = "1.0"
thiserror = "2.0.12"
